
run_infinite: False
display: False

save:
  save_pkl: True
  save_pkl_overwrite: True
  save_pkl_path: "output/boundary_t1_"

problem:
  vector_field: vf_flow_incompressible
  initial_condition: ic_flow_basic

constants:
  horizontal_diffusivity: 0.5
  horizontal_viscosity: 1
  reference_density: 0.1

spatial_discretisation:
  lat_first: -1.57
  lat_final: 1.57
  lat_n:     45
  lng_first: -3.14
  lng_final: 3.14
  lng_n:     90

  

temporal_discretisation_finite:
  t_first: 0
  t_final: 15
  t_n: 250

temporal_discretisation_infinite: 
  t_first: 0
  t_each_solve: 0.1
  t_n_each_solve: 100

solver_options:
  type: 'diffrax_Euler'
  finite_diff_dt: 0.001
  stepsize_controller:
    type: 'diffrax_ConstantStepSize'
    pcoeff: 0.3
    icoeff: 0.4
    rtol: 1.0e-3
    atol: 1.0e-3
    dtmax: 0.1
  

map:
  mask_image_path_relative: True
  mask_image_path: "resources/map/equirectangular_1920_wikipedia_blue_marble_2002.png"