rest:
  url: "https://example.org/primenumbers/v1"
  port: 8443

prime_numbers: [2, 3, 5, 7, 11, 13, 17, 19]

map:
  mask_image_path_relative = True
  mask_image_path = "resources\map\equirectangular_1920_wikipedia_blue_marble_2002.png"