
run_infinite: False

problem:
  vector_field: vf_heat_equation
  initial_condition: ic_heat_quartic


spatial_discretisation:
  x_first: -1
  x_final: 1
  x_n: 200

temporal_discretisation_finite:
  t_first: 0
  t_final: 1
  t_n: 200

temporal_discretisation_infinite: 
  t_first: 0
  t_each_solve: 0.5
  t_n_each_solve: 100

solver_options:
  type: diffrax_Tsit5
  finite_diff_dt: 0.01
  stepsize_controller:
    type: 'diffrax_PIDController'
    pcoeff: 0.3
    icoeff: 0.4
    rtol: 1.0e-10
    atol: 1.0e-10
    dtmax: 0.001
  

map:
  mask_image_path_relative: True
  mask_image_path: "resources\\map\\equirectangular_1920_wikipedia_blue_marble_2002.png"